version: '3'

services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && echo \"from django.contrib.auth.models import User; User.objects.create_superuser('${DJANGO_SUPERUSER_USERNAME}', '${DJANGO_SUPERUSER_EMAIL}', '${DJANGO_SUPERUSER_PASSWORD}')\" | python manage.py shell && gunicorn --workers 3 --threads 2 --bind 0.0.0.0:8000 --timeout 300 evently.wsgi:application"
    expose:
      - "8000"

    depends_on:
      - db
    volumes:
      - ./backend/staticfiles:/src/staticfiles
    # env_file:
    #   - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evently_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: 
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./backend/staticfiles:/src/staticfiles

volumes:
  postgres_data:
