version: '3'

services:
  api:
    build: ./backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --workers 3 --threads 2 --bind 0.0.0.0:8000 --timeout 300 evently.wsgi:application"
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evently_db
    volumes:
      - postgres_data:/var/lib/postgresql/data


  nginx:
    build: 
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    ports:
      - "80:80"

volumes:
  postgres_data: