version: '3'

services:
  api:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 evently.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evently_db
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
